# Nord-inspired theme
format = """
[$username]($username.style)\
[@$hostname]($hostname.style)\
[($directory)]($directory.style)\
[$git_branch$git_status]($git_branch.style)\
[$nodejs$python$rust$golang]($nodejs.style)\
$character
"""

[username]
style = "blue bold"
show_always = true

[hostname]
style = "cyan bold"

[directory]
style = "blue"
truncation_length = 2

[git_branch]
style = "purple"

[git_status]
style = "red"

[nodejs]
style = "green"

[python]
style = "yellow"

[rust]
style = "red"

[golang]
style = "cyan"

[character]
success_symbol = "[▶](green)"
error_symbol = "[▶](red)"
