# Dracula-inspired theme
format = """
[$username]($username.style)\
[@$hostname]($hostname.style)\
[ $directory]($directory.style)\
[$git_branch$git_status]($git_branch.style)\
[$nodejs$python$rust$golang]($nodejs.style)\
$character
"""

[username]
style = "purple bold"
show_always = true

[hostname]
style = "green bold"

[directory]
style = "cyan bold"
truncation_length = 3

[git_branch]
style = "purple"
symbol = " "

[git_status]
style = "red"

[nodejs]
style = "green"
symbol = " "

[python]
style = "yellow"
symbol = " "

[rust]
style = "red"
symbol = " "

[golang]
style = "cyan"
symbol = " "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
