# Basic example configuration
format = "$username@$hostname:$directory$git_branch$character"

[username]
style = "white"

[hostname]
style = "white"

[directory]
style = "blue"

[git_branch]
style = "yellow"

[character]
success_symbol = "$ "
error_symbol = "$ "
