# Basic Starship configuration
format = """
[$username]($username.style)\
[@$hostname]($hostname.style)\
[($directory)]($directory.style)\
[$git_branch$git_status]($git_branch.style)\
[$nodejs$python$rust$golang]($nodejs.style)\
$character
"""

[username]
style = "blue bold"
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "green bold"
format = "[$hostname]($style)"

[directory]
style = "cyan"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style)"

[git_branch]
style = "purple"
format = "[$symbol$branch]($style)"

[git_status]
style = "red"
format = "[$all_status$ahead_behind]($style)"

[nodejs]
style = "green"
format = "[$symbol($version)]($style)"
symbol = " "

[python]
style = "yellow"
format = "[$symbol$pyenv_prefix($version)($virtualenv)]($style)"
symbol = " "

[rust]
style = "red"
format = "[$symbol($version)]($style)"
symbol = " "

[golang]
style = "cyan"
format = "[$symbol($version)]($style)"
symbol = " "

[character]
success_symbol = "[▶](green)"
error_symbol = "[▶](red)"
