# Minimal Starship configuration
format = "$username@$hostname:$directory$git_branch$character"

[username]
style = "blue"

[hostname]
style = "green"

[directory]
style = "cyan"

[git_branch]
style = "purple"

[character]
success_symbol = "$ "
error_symbol = "$ "
