format = """
╔══════════════════════════════════════════════════╗
║ User: [$username]($username.style) @ Host: [$hostname]($hostname.style) ║
║ Path: [$directory]($directory.style)             ║
║ Git:  $git_branch$git_status                     ║
║ Lang: $nodejs$python$rust$go                     ║
╚══════════════════════════════════════════════════╝
$character"""

[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"

[hostname]
ssh_only = false
style = "bold green"

[directory]
style = "bold cyan"
truncation_length = 3

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
format = '[$all_status]($style) '

[nodejs]
symbol = "⬢ "
style = "bold green"
format = "[$symbol$version]($style) "

[python]
symbol = " "
style = "bold yellow"
format = '[$symbol$version]($style) '

[rust]
symbol = " "
style = "bold orange"
format = "[$symbol$version]($style) "

[golang]
symbol = " "
style = "bold cyan"
format = "[$symbol$version]($style) "

[character]
success_symbol = "[▶](bold green)"
error_symbol = "[▶](bold red)"
