format = """
╭─[$username@$hostname]-[$directory]
├─[$git_branch$git_status]
├─[$nodejs$python$rust]
╰─$character"""

[username]
show_always = true
style_user = "bold cyan"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold green"
format = "[$hostname]($style)"

[directory]
style = "bold blue"
format = "[$path]($style)"
truncation_length = 4

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style)"

[git_status]
style = "bold red"
format = '[$all_status$ahead_behind]($style)'

[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol$version]($style) "

[python]
symbol = " "
style = "bold yellow"
format = '[$symbol$version]($style) '

[rust]
symbol = " "
style = "bold orange"
format = "[$symbol$version]($style) "

[character]
success_symbol = "[➤](bold green)"
error_symbol = "[➤](bold red)"
