tomlformat = """
┌─[$username@$hostname]-[$directory]
└─$git_branch$git_status$character"""

[username]
format = "[$user]($style)"
style_user = "bold green"
style_root = "bold red"
show_always = true

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold green"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold cyan"
truncation_length = 8
truncate_to_repo = false

[git_branch]
format = "[git:($branch)]($style) "
style = "bold purple"

[git_status]
format = '[\[$all_status$ahead_behind\]]($style) '
style = "bold red"

[character]
success_symbol = "[#](bold green)"
error_symbol = "[#](bold red)"
