format = """$directory$git_status$line_break[$character](bold yellow)"""
[character]
success_symbol = "ᗧ"
error_symbol = "Ͼ"
[git_status]
format = "[$all_status$progress]($style)"
progress = "$(echo -e "\U1F47E")"